---
- name: Install Docker and Docker Compose
  hosts: localhost
  become: yes
  tasks:
    - name: Add Docker repo
      yum_repository:
        name: docker-ce
        description: Docker CE Repo
        baseurl: https://download.docker.com/linux/centos/7/x86_64/stable
        gpgcheck: yes
        gpgkey: https://download.docker.com/linux/centos/gpg

    - name: Install Docker packages
      yum:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
        state: present

    - name: Enable and start Docker
      service:
        name: docker
        state: started
        enabled: yes

    - name: Add user to docker group
      user:
        name: fimtiaz
        groups: docker
        append: yes

